version: "3.9"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "mydb"
      MYSQL_PASSWORD: "1234"
      MYSQL_ROOT_PASSWORD: "1234"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my-network
  # phpmyadmin:
  #   depends_on:
  #     - db
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     - PMA_HOST=db
  #     - PMA_PORT=3306
  #   networks:
  #     - my-network
  #   ports:
  #     - 8001:80
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/data"
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
  mailpit:
    image: "axllent/mailpit:latest"
    ports:
      - "${FORWARD_MAILPIT_PORT:-1025}:1025"
      - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"

  localtunnel:
    image: efrecon/localtunnel
    restart: on-failure
    command: lt --local-host host.docker.internal --port 4000 --subdomain upload-virtualparkin --secure

networks:
  my-network:
    driver: bridge
volumes:
  db_data:
  redis_data:
