version: "3.9"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "mydb"
      MYSQL_PASSWORD: "1234"
      MYSQL_ROOT_PASSWORD: "1234"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my-network
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - my-network
    ports:
      - 8001:80
networks:
  my-network:
    driver: bridge
volumes:
  db_data:
